---
title: "hyperparameter_tuning"
author: "Mohd-Javed"
date: "4/13/2021"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = TRUE,warning = FALSE,message = FALSE,dpi = 180,fig.width = 8,fig.height = 5)
```

```{r}
library(readr)
library(magrittr)
library(dplyr)
library(ggplot2)
library(rmarkdown)
library(tidyverse)

```


```{r}
sf_trees <- read_csv("sf_trees.csv")
```

```{r}
trees_df <- sf_trees %>%
  mutate(
    legal_status = case_when(legal_status == "DPW Maintained" ~ legal_status, TRUE ~
                               "Other"),
    plot_size = parse_number(plot_size)
  ) %>%
  select(-address) %>%
  na.omit() %>%
  mutate_if(is.character, factor)
```

```{r}
skimr::skim(trees_df)
```
```{r}
trees_df%>%
  ggplot(aes(longitude,latitude,color=legal_status))+
  geom_point(size=.2)+
  theme_classic()

```

```{r}
trees_df%>%
  count(legal_status,caretaker)%>%
  add_count(caretaker,wt=n,name="caretaker_count")%>%
  filter(caretaker_count>50)%>%
  group_by(legal_status)%>%
  mutate(percent_legal=n/sum(n))%>%
  ggplot(aes(percent_legal,caretaker,fill=legal_status))+
  geom_col(position = "dodge")
```

```{r}
library(tidymodels)
set.seed(73)
trees_split<-initial_split(trees_df,strata=legal_status)
train_set<-training(trees_split)
test_set<-testing(trees_split)

```

```{r}
tree_rec<-recipe(legal_status~.,data=train_set)%>%
  update_role(tree_id,new_role = "ID")%>%
  step_other(species,caretaker,threshold = .01)%>%
  step_other(site_info,threshold =0.005)%>%
  step_dummy(all_nominal(),-all_outcomes())%>%
  step_date(date,features=c("year"))%>%
  step_rm(date)%>%
  step_downsample(legal_status)

tree_prep<-prep(tree_rec)
juiced<-juice(tree_prep)

```

```{r}
tune_spec<-rand_forest(
  mtry = tune(),
  trees = 1000,
  min_n = tune()
)%>%
  set_mode("classification")%>%
  set_engine("ranger")

```



```{r}
tune_wf<-workflow()%>%
  add_recipe(tree_rec)%>%
  add_model(tune_spec)

```

```{r}
set.seed(234)
trees_folds<-vfold_cv(train_set)
doParallel::registerDoParallel()
library(ranger)
set.seed(345)
tune_res<-tune_grid(
  tune_wf,
  resamples = trees_folds,
  grid=20
)
```

